name: Sync Google Sheets to Data Files

on:
  schedule:
    - cron: "*/1 * * * *"  # every 30 minutes
  workflow_dispatch:         # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download definition.json from Google Sheets
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1ioqhEoWUF4kuke9kuyPTJ9iPsuHIbHzo/export?format=csv" \
            -o definition.csv
          # optional: convert CSV → JSON if you're actually storing as JSON
          # python3 -c 'import csv, json; print(json.dumps(list(csv.DictReader(open("definition.csv"))), indent=2))' > definition.json

      - name: Download user_progress.csv from Google Sheets
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1bfFIBtzalMzUBCkfJ_5W3WrCMRDMSMPY-9cHBhxVVuM/export?format=csv" \
            -o user_progress.csv

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if git diff --quiet user_progress.csv definition.csv definition.json 2>/dev/null; then
            echo "No changes."
          else
            git add user_progress.csv definition.csv definition.json || true
            git commit -m "🔄 Auto-update from Google Sheets"
            git push
          fi
